version: '2'

services:
  redis:
    image: redis

  logstash:
    image: $REGISTRY_HOST/$CI_PROJECT_PATH:$CI_COMMIT_TAG
    environment:
      - ENVIRONMENT=$CI_JOB_NAME
      - ELASTICSEARCH_URL=192.168.250.9
      - "XPACK_MONITORING_ELASTICSEARCH_URL=http://192.168.250.9:9200"