image: docker:latest

stages:
  - build
  - release

before_script:
  - docker login -u $REGISTRY_ID -p $REGISTRY_PASS $REGISTRY_HOST

build:
  stage: build
  script:
    - docker build -t $REGISTRY_HOST/$CI_PROJECT_PATH:$CI_COMMIT_SHA .
    - docker push $REGISTRY_HOST/$CI_PROJECT_PATH:$CI_COMMIT_SHA
  only:
    - develop
    - master

release:
  stage: release
  script:
    - docker pull $REGISTRY_HOST/$CI_PROJECT_PATH:$CI_COMMIT_SHA
    - docker tag $REGISTRY_HOST/$CI_PROJECT_PATH:$CI_COMMIT_SHA $REGISTRY_HOST/$CI_PROJECT_PATH:$CI_COMMIT_TAG
    - docker push $REGISTRY_HOST/$CI_PROJECT_PATH:$CI_COMMIT_TAG
  only:
    - tags
