version: '2'
services:
  web:
    image: $REGISTRY_HOST/$CI_PROJECT_PATH:$CI_COMMIT_TAG
    environment:
      ENVIRONMENT: $CI_JOB_NAME
      LOGS_ENV_SCHEME: tcp
      LOGS_ENV_HOST: redis.backend-api-logs
      LOGS_ENV_PORT: 6379
      LOGS_ENV_TYPE: Configs
      LOGS_ENV_REDIS_KEY: backend-api-logs
      LOGS_ENV_CHANNEL: configs
    stdin_open: true
    secrets:
    - mode: '0400'
      source: JWT_SECRET
    tty: true
    labels:
      io.rancher.container.pull_image: always
  api:
    image: rancher/lb-service-haproxy:v0.9.1
    expose:
    - 80:80/tcp
    labels:
      io.rancher.container.agent.role: environmentAdmin,agent
      io.rancher.container.agent_service.drain_provider: 'true'
      io.rancher.container.create_agent: 'true'

secrets:
  JWT_SECRET:
    external: 'true'