version: '2'
services:
  web:
    image: $REGISTRY_HOST/$CI_PROJECT_PATH:$CI_COMMIT_TAG
    environment:
      DB_ENV_COREDB_HOST: coredb.common.bankmedia
      DB_ENV_COREDB_DATABASE: webhard_core
      DB_ENV_COREDB_USER: backend
      DB_ENV_MDB_HOST: mdb.yesfile.bankmedia
      DB_ENV_MDB_DATABASE: webhard
      DB_ENV_MDB_USER: backend
      DB_ENV_SDB_DATABASE: webhard
      DB_ENV_SDB_USER: backend
      LOGS_ENV_SCHEME: tcp
      LOGS_ENV_HOST: redis.backend-api-logs
      LOGS_ENV_PORT: 6379
      LOGS_ENV_TYPE: Filters
      LOGS_ENV_REDIS_KEY: backend-api-logs
      LOGS_ENV_CHANNEL: filters
    stdin_open: true
    secrets:
    - mode: '0400'
      source: JWT_SECRET
    - mode: '0400'
      source: DB_ENV_COREDB_PASSWORD
    - mode: '0400'
      source: DB_ENV_MDB_PASSWORD
    - mode: '0400'
      source: DB_ENV_SDB_PASSWORD
    tty: true
    labels:
      io.rancher.container.pull_image: always
  api:
    image: rancher/lb-service-haproxy:v0.9.1
    expose:
    - 80:80/tcp
    labels:
      io.rancher.container.agent.role: environmentAdmin,agent
      io.rancher.container.agent_service.drain_provider: 'true'
      io.rancher.container.create_agent: 'true'

secrets:
  JWT_SECRET:
    external: 'true'
  DB_ENV_COREDB_PASSWORD:
    external: 'true'
  DB_ENV_MDB_PASSWORD:
    external: 'true'
  DB_ENV_SDB_PASSWORD:
    external: 'true'