version: '2'
services:
  redis:
    image: redis:4.0

  web:
    image: $REGISTRY_HOST/$CI_PROJECT_PATH:$CI_COMMIT_TAG
    environment:
      ENVIRONMENT: $CI_JOB_NAME
      JWT_SECRET_FILE: /run/secrets/JWT_SECRET
      REDIS_ENV_SCHEME: tcp
      REDIS_ENV_HOST: redis.backend-api-auth
      LOGS_ENV_SCHEME: tcp
      LOGS_ENV_HOST: redis.backend-api-logs
      LOGS_ENV_TYPE: Auth
      LOGS_ENV_REDIS_KEY: backend-api-logs
      LOGS_ENV_CHANNEL: auth
    stdin_open: true
    secrets:
    - mode: '0444'
      uid: '0'
      gid: '0'
      source: JWT_SECRET
      target: ''
    tty: true
    labels:
      io.rancher.container.pull_image: always

  api:
    image: rancher/lb-service-haproxy:v0.9.1
    expose:
    - 80:80/tcp
    labels:
      io.rancher.container.agent.role: environmentAdmin,agent
      io.rancher.container.agent_service.drain_provider: 'true'
      io.rancher.container.create_agent: 'true'

secrets:
  JWT_SECRET:
    external: 'true'