#!/bin/bash
set -e

# first arg is `-f` or `--some-option`
if [ "${1#-}" != "$1" ]; then
	set -- apache2-foreground "$@"
fi

# load environment from rancher secrets
if [ -d /run/secrets ]; then
	for f in /run/secrets/*; do
		var=`basename $f`
		val="$(< "/run/secrets/$var")"

		export "$var"="$val"
	done
fi

exec "$@"